### ISSUE TITLE
Z height position is displayed incorrect 

### ISSUE THREAD

**Issue by paranguiz** [CR6Community/cr6community.github.io#3]
![photo_2021-01-27_16-38-22](https://user-images.githubusercontent.com/12844752/106044164-1ce8be80-60be-11eb-836c-5e7d0d2d183b.jpg)
![photo_2021-01-27_16-38-15](https://user-images.githubusercontent.com/12844752/106044170-1d815500-60be-11eb-9418-155ffe37f4e1.jpg)

When printing the height Z value is shown as divided by 10, example display value: 5.35 , correct value: 53.5

**Comment by BubuMVX** [comment]
Hi @paranguiz and thanks for your report.

This issue has already been raised and fixed, you can find the reports and discussions here:

- https://github.com/CR6Community/CR-6-touchscreen/issues/23
- https://github.com/CR6Community/Marlin/issues/111

Note that this is the "knowledge base" repository. You'll find the motherboard and the touchscreen sources, firmwares and issues on their respective repositories:

- https://github.com/CR6Community/Marlin
- https://github.com/CR6Community/CR-6-touchscreen/

Thanks anyway for taking the time to test and report that.
